---
title: Checking my order's status
---
flowchart LR
    subgraph Check order status
        direction LR
        C["Go to\nmy orders"]
        D["Go to order\nin question"]
        E["Check\nstatus"]
    end
    C --> D --> E