---
title: Making an order
---
flowchart LR
    subgraph Inspect shopping cart
        A["Go to\nshopping cart"]
        B["Change \nquantity"]
        C["Remove \nitem"]
        D["Proceed \nto checkout"]
    end
    subgraph Provide information
        E["Choose \ndelivery address"]
        F["Select \nshipping method"]
        G["Select \npayment method"]
        H["Confirm \norder"]
    end
    A --> B --> C --> D --> E --> F --> G --> H