---
title: Writing a review
---
flowchart LR
    subgraph Enter online shop
        A["Visit\nwebsite"]
        B["Log in"]
    end
    subgraph Go to ordered item
        C["Go to \nmy orders"]
        D["Go to \norder in question"]
        E["Select item \nto review"]
    end
    subgraph Write review
        F["Choose \ntitle"]
        G["Write \ntext"]
        H["Submit \nreview"]
    end
    A --> B --> C --> D --> E --> F --> G --> H