---
title: Looking for a specific product
---
flowchart LR
    subgraph Look for specific product
        direction LR
        C["Check out\ncategories"]
        D["Go to\npromising category"]
        E["Apply filter\nto category"]
        F["Scroll through\nproducts"]
        G["Go to\npromising product"]
        H["Read product\ndescription"]
        I["Check out\nproduct variants"]
        J["Read\nreviews"]
        K["Decide if\nproduct found"]
    end
    C --> D --> E --> F --> G --> H --> I --> J --> K