---
title: Adding a new product that has multiple variants
---
flowchart LR
    subgraph Enter online shop
        A["Visit\nwebsite"]
        B["Log in\nas employee"]
    end
    subgraph Add new product
        C["Click\n'Add Product'"]
        D["Click\n'Add Variant'"]
    end
    subgraph "Add variant (iteratively)"
        E["Provide\nname"]
        F["Set\nvisibility"]
        G["Write\ndescription"]
        H["Set\nretail price"]
        I["Set current\nprice (optional)"]
        J["Add\nimages"]
    end
    subgraph Finish adding product
        K["Select\ndefault variant"]
        L["Add product\nto categories"]
        M["Click\n'Submit'"]
    end
    A --> B --> C --> D --> E --> F --> G --> H --> I --> J --> K --> L --> M