---
title: Looking for a specific product (Alternative 1)
---
flowchart LR
subgraph Enter online shop
        A["Visit\nwebsite"]
        B["Log in\n(optional)"]
end
subgraph Look for specific product
        C["Go to\nsearch"]
        D["Search with\ntext input"]
        E["Apply filter to\nsearch results"]
        F["Scroll through\n(filtered) search results"]
        G["Go to\npromising product"]
        H["Read\nproduct description"]
        I["Check out\nproduct variants"]
        J["Read\nreviews"]
        K["Decide if\nproduct found"]
end
        A-->B-->C-->D-->E-->F-->G-->H-->I-->J-->K