---
title: Adding a new wishlist
---
flowchart LR
    subgraph Add wishlist
        direction LR
        C["Go to \nmy wishlists"]
        D["Click on \n'Add wishlist'"]
        E["Choose \nname"]
        F["Confirm \ncreation"]
    end
    C --> D --> E --> F