---
title: Adding a new product that only has one variant
---
flowchart LR
    subgraph Enter online shop
        A[Visit\nwebsite]
        B[Log in\nas employee]
    end
    subgraph Add new product
        C["Click\n'Add Product'"]
        D[Provide\nname]
        E[Set\nvisibility]
        F[Write\ndescription]
        G[Set\nretail price]
        H["Set current\nprice (optional)"]
        I[Add\nimages]
        J[Add product\nto categories]
        K["Click\n'Submit'"]
    end
A-->B-->C-->D-->E-->F-->G-->H-->I-->J-->K