---
title: Adding a new wishlist
---
flowchart LR
    subgraph Enter online shop
        A["Visit \nwebsite"]
        B["Log in"]
    end
    subgraph Add wishlist
        C["Go to \nmy wishlists"]
        D["Click on \n'Add wishlist'"]
        E["Choose \nname"]
        F["Confirm \ncreation"]
    end
    A --> B --> C --> D --> E --> F