---
title: Browsing the online shop
---
flowchart LR
    subgraph Enter online shop
        A[Visit\nwebsite]
        B["Log in\n(optional)"]
    end
    subgraph Browse online shop
        C[Scroll through\nstart page]
        D[Check out\ncategories]
        E[Go to\ncategory]
        F[Apply filter\nto category]
        G[Scroll through\nproducts]
        H[Go to\nproduct]
        I[Read\nreview]
        J[Read another\nreview]
        K[Check out\nproduct variants]
        L[Add product to\nshopping cart]
    end
    A --> B --> C --> D --> E --> F --> G --> H --> I --> J --> K --> L