---
title: Writing a review (Alternativ 1)
---
flowchart LR
    subgraph Enter online shop
        A["Visit \nwebsite"]
        B["Log in"]
    end
    subgraph Go to product
        C["Navigate \nto product"]
        D["Go to \nReviews section"]
        E["Click on \n'Review'"]
    end
    subgraph Write review
        F["Choose \ntitle"]
        G["Write \ntext"]
        H["Submit \nreview"]
    end
    A --> B --> C --> D --> E --> F --> G --> H