---
title: Adding an item to the wishlist
---
flowchart LR
    subgraph Browse online shop
        direction LR
        C["Scroll through\nstart page"]
        D["Check out\ncategories"]
        E["Go to\ncategory"]
        F["Apply filter\nto category"]
        G["Scroll through\nproducts"]
        H["Go to\nproduct"]
        I["Read\nreview"]
        J["Read another\nreview"]
        K["Check out\nproduct variants"]
        L["Click on\n'Add to wishlist'"]
        M["Choose\nwishlist"]
    end
    C --> D --> E --> F --> G --> H --> I --> J --> K --> L --> M