---
title: Returning an ordered item
---
flowchart LR
subgraph Enter online shop
        A["Visit \nwebsite"]
        B["Log in"]
    end
subgraph Initiate return
        C["Go to \nmy orders"]
        D["Go to \norder in question"]
        E["Select items \nto return"]
        F["Create \nreturn request"]
        G["Wait for \nconfirmation"]
        H["Check \nreturn instructions"]
        I["Print \nshipping label"]
        J["Receive \nrefund"]
        end
        A-->B-->C-->D-->E-->F-->G-->H-->I-->J