name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Render HyLiMo diagrams
        run: npm run render-diagrams
      - name: Update GraphQL docs
        run: npm run update-graphql-docs
      - name: Build website
        run: npm run build
      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          force_orphan: true
          publish_branch: main